id: pipeline1
bioflowId: pipeline123
type: pipeline
name: my pipeline
description:
  -"this tool will list directories"
  -"this tool will list all linux directories for a given input directory parameter"
website: http://www.google.com
version: 1.0.0
icon: here you can place the hexadecimal value of an icon in png format
maintainer:
  -fullname: XXXXXXXX
  email: XXXXXXX@gmail.com
  username: XXXXXXX

references:
  - name: "name of the reference"
    description: "long or short snippet of a description goes here"
    website: http://www.ncbi.nlm.gov.nl

steps:
  - id: 1
    bioflowId: xdir3525
    name: 1
    description: this is a tool that will list all linux directories for a given input directory parameter
    discussions:
      - this tool will list directories
      - this tool will list all linux directories for a given input directory parameter
    website: http://hub.bioflows.io
    version: 1.0.0
    icon: here you can place hexadecimal value of an icon in png format
    # shadow property indicates that this tool will have no output, it exists in a pipeline perhaps to modify some pipeline config param values or act
    # as a decision tool
    shadow: false
    maintainer:
      -fullname: XXXXXXXX
      email: xxxx@XXX.com
      username: xxxx

    references:
      - name: "name of the reference"
        description: "long or short snippet of a description goes here"
        website: http://www.ncbi.nlm.gov.nl

    inputs:
      - type: string
        displayname: the input directory for the command
        name: input_dir
        description: long or short description about the parameter goes here
        value: /your/dir/location
    scripts:
      - type: js
        before: true
        order: 1
        code: >
          self.input_dir = "/your/dir/location";
      - type: js
        order: 2
        before: true
        code: >
          self.input_dir = "/your/other/dir";
    # this tool has no outputs
    command: ls -ll {{input_dir}}

  - id: 2
    bioflowId: xdir3526
    name: 2
    description: this is a tool that will list all linux directories for a given input directory parameter
    discussions:
      - this tool will list directories
      - this tool will list all linux directories for a given input directory parameter
    website: http://hub.bioflows.io
    version: 1.0.0
    icon: here you can place hexadecimal value of an icon in png format
    # shadow property indicates that this tool will have no output, it exists in a pipeline perhaps to modify some pipeline config param values or act
    # as a decision tool
    shadow: false
    maintainer:
      -fullname: XXXXXXXXX
      email: xx@xx.com
      username: XXXX

    references:
      - name: "name of the reference"
        description: "long or short snippet of a description goes here"
        website: http://www.ncbi.nlm.gov.nl
    notification:
      to: xx@xx.com
      title: "Step 2 has finished"
      body: "Step 2 has finished"


    inputs:
      - type: string
        displayname: the input directory for the command
        name: input_dir
        description: long or short description about the parameter goes here
        value: /your/dir
    scripts:
      - type: js
        before: true
        order: 2
        code: >
          self.input_dir = "/your/dir/location";
      - type: js
        order: 1
        before: true
        code: >
          self.input_dir = "/your/dir/location";
    # this tool has no outputs
    command: ls -ll {{input_dir}} > myfile.txt

  - id: 3
    bioflowId: xdir3528
    depends: 1,2
    name: 3
    description: this is a tool that will list all linux directories for a given input directory parameter
    discussions:
      - this tool will list directories
      - this tool will list all linux directories for a given input directory parameter
    website: http://hub.bioflows.io
    version: 1.0.0
    icon: here you can place hexadecimal value of an icon in png format
    # shadow property indicates that this tool will have no output, it exists in a pipeline perhaps to modify some pipeline config param values or act
    # as a decision tool
    shadow: false
    maintainer:
      -fullname: XXXXXXXXX
      email: xx@xx.com
      username: XXXX

    references:
      - name: "name of the reference"
        description: "long or short snippet of a description goes here"
        website: http://www.ncbi.nlm.gov.nl

    inputs:
      - type: string
        displayname: the input directory for the command
        name: input_dir
        description: long or short description about the parameter goes here
        value: /your/dir
    scripts:
      - type: js
        before: true
        order: 1
        code: >
          self.input_dir = "/your/dir/location";
      - type: js
        order: 2
        before: true
        code: >
          self.input_dir = "/your/dir/location";
    # this tool has no outputs
    command: ls -ll {{input_dir}}

  - id: 5
    bioflowId: xdir3529
    depends: 1,3
    name: 5
    description: this is a tool that will list all linux directories for a given input directory parameter
    discussions:
      - this tool will list directories
      - this tool will list all linux directories for a given input directory parameter
    website: http://hub.bioflows.io
    version: 1.0.0
    icon: here you can place hexadecimal value of an icon in png format
    # shadow property indicates that this tool will have no output, it exists in a pipeline perhaps to modify some pipeline config param values or act
    # as a decision tool
    shadow: false
    maintainer:
      -fullname: XXXXXXXXX
      email: xx@xx.com
      username: XXXX

    references:
      - name: "name of the reference"
        description: "long or short snippet of a description goes here"
        website: http://www.ncbi.nlm.gov.nl

    inputs:
      - type: string
        displayname: the input directory for the command
        name: input_dir
        description: long or short description about the parameter goes here
        value: /your/dir
    scripts:
      - type: js
        before: true
        order: 1
        code: >
          self.input_dir = "/your/dir/location";
      - type: js
        order: 2
        before: true
        code: >
          self.input_dir = "/your/dir/location";
    # this tool has no outputs
    command: ls -ll {{input_dir}}

  - id: 4
    bioflowId: xdir3529
    depends: 3,5
    name: 4
    description: this is a tool that will list all linux directories for a given input directory parameter
    discussions:
      - this tool will list directories
      - this tool will list all linux directories for a given input directory parameter
    website: http://hub.bioflows.io
    version: 1.0.0
    icon: here you can place hexadecimal value of an icon in png format
    # shadow property indicates that this tool will have no output, it exists in a pipeline perhaps to modify some pipeline config param values or act
    # as a decision tool
    shadow: false
    maintainer:
      -fullname: XXXXXXXXX
      email: xx@xx.com
      username: XXXX

    references:
      - name: "name of the reference"
        description: "long or short snippet of a description goes here"
        website: http://www.ncbi.nlm.gov.nl

    inputs:
      - type: string
        displayname: the input directory for the command
        name: input_dir
        description: long or short description about the parameter goes here
        value: /your/dir
    scripts:
      - type: js
        before: true
        order: 1
        code: >
          self.input_dir = "/your/dir/location";
      - type: js
        order: 2
        before: true
        code: >
          self.input_dir = "/your/dir/location";
    # this tool has no outputs
    command: ls -ll {{input_dir}}